### ISSUE TITLE
Device freezes

### ISSUE THREAD

**Issue by tb59427** [SashLi/FreeVarioGauge#3]
Hi guys,

I am currently trying to understand the root cause for OpenVario freezes (see [here](https://github.com/Openvario/meta-openvario/issues/304)). I stumbled across your repository of OV images a while ago and installed 22028 for 5.7 on my Stefly. The image are all numbered 22028. Now this alternative OV shell reports these builds as 21350. Could you shed some light on this, please? 

Were they build in Feb of 22 or late 21? Also, did you change the build to use a non standard (at that time) kernel? The kernel version for 22028 is reported as 5.10.2 which is fairly old - but runs stable on an OV, while the new 5.15.x kernels seem to erradically crash - at least on some OVs . As I am trying to understand where it all started with those freezes, your feedback and insights are highly appreciated.

cheers
Torsten

**Comment by Blaubart** [comment]
Hi Torsten,

Why the image is outputting as 21350 is strange. The images were compiled in January 2022. We also never made any changes to the kernel. We always checked out from OpenVario's git, made our small changes, and then compiled. I could only imagine that although I compiled in January 2022, no changes were made to OpenVario, which is why the old version remained in the image. I can't explain why a different kernel was used!

regards
Dirk

> Am 24.05.2022 um 14:17 schrieb D-2402 ***@***.***>:
> 
> Hi guys,
> 
> I am currently trying to understand the root cause for OpenVario freezes (see here <https://github.com/Openvario/meta-openvario/issues/304>). I stumbled across your repository of OV images a while ago and installed 22028 for 5.7 on my Stefly. The image are all numbered 22028. Now this alternative OV shell reports these builds as 21350. Could you shed some light on this, please?
> 
> Were the build in Feb of 22 or late 21? Also, did you change the build to use a non standard (at that time) kernel? The kernel version for 22028 is reported as 5.10.2 which is fairly old - but runs stable on an OV, while the new 5.15.x kernels seem to erradically crash - at least on some OVs . As I am trying to understand where it all started with those freezes, your feedback and insights are highly appreciated.
> 
> cheers
> Torsten
>

**Comment by tb59427** [comment]
Hi Dirk,

thanks for the rapid turnaround on this :-) Your answer implies that the switch to newer kernels must have been made after 22028 and 22086 - apparently the first image where crashed occur. 

thanks for your help
cheers
Torsten
